// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDao-OzmRBuePTS_Vz67Q-VNAKHvvnFKKs',
    appId: '1:127690619516:web:a96a4892aa4637739c67f9',
    messagingSenderId: '127690619516',
    projectId: 'taxi-tao',
    authDomain: 'taxi-tao.firebaseapp.com',
    storageBucket: 'taxi-tao.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJLBH6CarkYVfp8utLDpRH1_XwV_XGb4k',
    appId: '1:127690619516:android:e84937ed6c83cb0f9c67f9',
    messagingSenderId: '127690619516',
    projectId: 'taxi-tao',
    storageBucket: 'taxi-tao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk7zpgRoqO4Wtsxa3guWBUQiJvL5Lh6QQ',
    appId: '1:127690619516:ios:946ca7545535db8a9c67f9',
    messagingSenderId: '127690619516',
    projectId: 'taxi-tao',
    storageBucket: 'taxi-tao.appspot.com',
    iosClientId: '127690619516-t4pf4sl0pudg6svnfrd8dla5j2rs5if1.apps.googleusercontent.com',
    iosBundleId: 'com.example.taosilApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk7zpgRoqO4Wtsxa3guWBUQiJvL5Lh6QQ',
    appId: '1:127690619516:ios:946ca7545535db8a9c67f9',
    messagingSenderId: '127690619516',
    projectId: 'taxi-tao',
    storageBucket: 'taxi-tao.appspot.com',
    iosClientId: '127690619516-t4pf4sl0pudg6svnfrd8dla5j2rs5if1.apps.googleusercontent.com',
    iosBundleId: 'com.example.taosilApp',
  );
}
